# Generated by Django 4.2 on 2025-09-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0006_giftcardshare"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservoucherredemption",
            name="bill_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total bill amount when voucher was redeemed",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="uservoucherredemption",
            name="bill_number",
            field=models.CharField(
                blank=True,
                help_text="Bill number or invoice number for the transaction",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="uservoucherredemption",
            name="discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discount amount applied from voucher",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="uservoucherredemption",
            name="final_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Final amount after discount",
                max_digits=10,
                null=True,
            ),
        ),
    ]
